- hosts: monitor
  roles:
    - citus-node
    - role: citus-coordinator
      vars:
        is_monitor: true
        pgpool_host: 10.210.14.48
        pgpool_pcp_pass: pgpool
        trust_networks: 
          - 10.210.14.0/24

- hosts: db
  serial: 1
  roles:
    - citus-node
    - role: citus-coordinator
      vars:
        monitor_host: 10.210.14.43
        trust_networks:
          - 10.210.14.0/24

- hosts: balancer
  roles:
    - citus-node
    - role: citus-pgpool
      vars:
        backends:
          - 10.210.14.44
          - 10.210.14.45
        pgpool_pcp_pass: pgpool
